---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCg1qPg0rXZzwRe1j08MnhLYu/iES9FRj6/fiuR5b7FphA/LfNTU3hFKW4UzjR4Sp9fiTSTOVBSk++z7bK/fcRbHaj7QYCV/qMyA5Hn4AiUiYyHQaOBL8T+sPa9X2bkAMLCtouU/I3fGbZNr/5O2bGwWYbZq28chRAPyOqNSo26jbz376Trpjb0KLhWVHq79fEC1i/I4wNz/2CJ+cshftsV2Xl+lvVapfshI1awMBTvyw2P8/+toyLA3wNXoS4U3wC30cs1Fhe+jbZtz5ibSbnaZWxDiJEMvKae+uNBn2LP9NqBO0KeoLQ2+wOTrGcieCtlexJzgEAqJUvcRh87qOUdGrAxWTrdmiMYFr6J4mIKgnDt6ayWqwsJMXiB+ZpX7e08fQ5Ya4OcStIeFg98/aISx1TFUPiTuPLwlsj1jbAU8U8SWyJH7iUoYZqed4S0wsPmO8CxTt3CfaGBuvAU0YDBTW+nTkbqB16Bu8a5/qnXJXlieeu7v96DFKIBP53O0kT2THrm5k/QyhocIJPraG26AK2ndglwJEpwYgvZyEOmOZuVi+LsvsrFCWb+ezShLi1skBAK+egH75HXRWTIMSn4hw37Tgp9W7n3ofNCCB8VO7qQbdVMc7J1yr3b3m1dvotdX4lCtNmLwnzr+laSSjmwH3AoY0dUnLDN6YVqlazHBfbJF8mLOnKeq7p/5Ts7u0jbWEO/az2Ofu+bIGeiooSLmOOw6kIGIQZ7Oy4rrenAXtErou4k4Y3243iiRwOsOO0=
    SONAR_JDBC_PASSWORD: AgBx2vyX8zd1W3NpRwtDxRPgylkzzry54nB8+iTp8UxdsUvloYIQWwMR4XME9U2YVZloK6s3fyipyllQQcROdvCv614pP+4JsniAsHe4SDrXKcxrr6WTL41hlEuSsAPezvpnM0fBGcdPvspOyGv4ysOWEtlOQ73krqfxcg76hiB40ranUg1k4qQ52xMWubeEw43kSMEV8S5Bt6dwZS/FJavnsBTKHp7TM5EgEI9JHZMFhb0Wnvmy8RVgMS44bfi70J9ur+iZryKIvSDjYFgZfnL39QKztnkBkaNLw2d556+3nCroD6DTHl1YbSXe2GKN+02SV4ImB7potqy3nQlO23AaXlzRu8aHLQuoorctdhw8Yy2l2Z8o55bxqofdzP6RipF+bNDXBeZwqW0WT73BKst37gzb+TWXF4pH++yV/5ZJG+luB7KTLX7nGjafg1ZjqmnPuao5wNd/cvaNK5ATO6peOsWKC5q3KUL0K/cHsHhvhkFIKOuD9VHS6CHPyqUySmpTYVHrfb3c6VWl0IXCBs8qF8/5+em+/DB0AI7aUo2T3tCF/h34cNvdMlmSSgP89mmnZPqyiC3UV7xuiRH9iJXMfw7SJv+gAIPN2KG3HgIA1Tk1wDlesYJdb9YDQk/53q7+mQVS8WEXomPpnW5yNCUKf4ZVzvNK1e2Q/pOLibO9JAIRl119qCkTxU7VW9erA2UKhDQgGZulk2cZcKwK2ZdoGuwVVNxRXBh2zcqs1aM8olP6HW+oh1lfPJWx9WoYj0g=
  template:
    metadata:
      name: sonarqube-db
      namespace: sonarqube
    type: Opaque
