---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCBgNVXJFrGYPB7T7uKBSl42knv3Q33iQL+mgQhamj6CvxFQijZhFK2dBvLWUBJtX8C/iNy+9V+nG7zYFCXMxT9NqmC11zeV/X9F5HaCjAwXjQmnCn3mm2D1mCR5du8W/PfKbnbehd9jB8xrSXlqAJx6NOJ6AOM5XEPBwLYxRin6YKeO6IZkqLKU+jXEMJXsOcW94ntBWseAdEc9NiYHQ7gC5cdOufYMmipTMHab5Q90RGMBEdkw7PBCSEn9lZ1g6WbXuJ1/5sqAmINHzNCCv7FIvG07h1yz06g57PzUnaVyvNCDX/5rNw1p/IfJwBuG5YLzL5YIPqIMYOLLloKoIyGWlLGDUkt+m59Y1JGMhDXUG7uhKCt6b4pk3/H1q+mjwuuKlpoWQA6rAsUAtWTw5cuCO5j7GML/lGUZCwREYmeUu6HPB2FWxSKIub/w7k+Raapytm0iOwuw20BKo29mlEcaVPlYSEO2J8vUbifRTDlxIM+vFqNlLPoOCCgBWLUgA1X1DGUDnzOorn/xGk1nCrt5zCuuFx4mhE1iPV4Efo0sF6f8YIG3BdVJjVaM6Zn7lrpedpqs89VopXK9gQBu5XgIkFQNLYX4j9Mh4uAGd37vbssdVU/yCPwYBzEP/6yyOOvf4RgtOtguGpuzuGX5/7v+ktB5i0cVph1nFr8QmQ7R7HdD2UjVRfiAupnfDuiIQmxRCoOTKfTnQ==
    admin-user: AgCoVx9s7Z7hkNDqPVcas3RUrF1d+ByEcRHVvtD3/A5PLVlRmJhgPWhQ6QNubs4ZpXPNDuQSNlydaj2GIjWWiJ4PGlbMVo04e/kFejjd1QwsmvwL2z6WMg3wVfNudhQ3XVPfAMfs1yhqX8NwstfEPz1LHjx383bCtBSE8DHYWIlcDERKqob0Uep+Zq1Yh30VuVW208hAorFa2pr84r+f8G8WMCxtgvLyv9r4i7CNNnHV2xjftdCf6czGyP8rr0g3oa3Ffm4+V8F3sVVMCJ/Z12+JFJF6VwYMTPJH5iO7geULfs6CkgYAV/1ietQwnAbqc48RrRXssZgp3xkzueyOYxwlA2CUzCY0H7LCdgdJMz0SXRptkE4JBDRq42KvCqkNItx+pn0+F+baqzyTiQrs5q4OXz3iX3x23CQGL+kV9P6raQwWV26sZqd9w16BiqoVz68zJ6aonFeS0Vaq5lGrK2MImlhHKvXLJQArcWZOWOozvdYRWcKvdSqmPzz6q1uakjV4KLDjbpLVaowy0waipzlDgYkN8pSk91+yISLuNGfC5R2dWRb0qFnrl7/sjX4aUI6wmnxzZTOwKrbh4RwPpydZ+tLKdX2fc9MGIMvIlWq3r5z8SWNHkyjZsrtxEhlO1tI0p1zUJDTHhS0sWndyvWl/0SkSmAuklfrniLYj242pevIPh+uzPBtP1dfNTE1TUbYTf74mYQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
