---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ragflow-config
  namespace: ragflow
spec:
  encryptedData:
    service_conf.yaml: AgBAszxTzapYwcDjiCv+SsNN4USY/ZD4YHs6NglCVxXsNfvjmS6sFCU9jAmNUfs0r2dLjwUMo8D7fPSHO00nN7LyzmY/Ju+KsnjwNrw3+xdm/skniQUNtdM0nrd9pLb7TX8k/v7QOpkv/LP7eWDaWluvMjLf8H2MLLSdoGAMwqz95sFPJPDAMOtAL3vNDRXOfBE8tIDZvCE8+J+pP7y0UR3cfIWN7Y0cZKK8owXlfQjFOuvWFR5Rq+A6XlPHKbboM4iW1RZgnlOeSYzIpbKUwSvORkj2pUBpZjqGiCc9Tf8kSeem3ZOd7aQCoG0ne7ux4YZZlyQPgycgjhT3PnPIkX8NKm44Cq07+GHwSrv96iX/7CKt9sGHFd1wD1iJac2cppCuunGojmHbXF1RbE7ymhhNRflAIgsYP5bKmoPEcJklUxiDbmt48tlFNTYlsQbchxPBv6bJoOA1aIgyxQJcEtSXDZhXPoS6BgcQ6BUrASdSdJtrqLOIhyHNo6+625W8m/nZAJqTb6hDWCCgiEJwTYtojhgSauSnY6xAFVwFOf64Qx3ZBUlmojzL94LGwYaMNPSHUeUq5qglrjLODMdwF05vNJU+MKPnqIDwQ2QPn4J2ePv1tOlmFpUvR5mUZ554B80T1ha1GoH1EnCFjvY5CBwzdsQDPueK6JC4h2KSS4OqqaAfKJGzd8aHZn7lt5S3TiWKNvS1yWSKrgjT7nwyy+X7oj99LbLWya4mPo1uY2SnuwVddcDYX9nhOWc9yGrCXNUJ0HK7iqRVDULa6HMzmtg6L4LZwnWW1tvaTGbcpVIaVhob1MKF62gK94w7UVlSsD1hOWgxSO2BUuiDKOCON7MNkUQSDIOFXFGgTS6T6uI6E/3p3suH5XWMeBTwYfNPKz84HpH8J3QjBB0X4oZocAyemvaBjA+vAKeGmhmoUHZcJk2fxGxraAS+9aY/Vwbrhuu+AO7lD0cDkPexmzwZZEDYGThYKsttgdRuSdwhk9raXUKoFS9ciHXkUfr81z8WvtxcO4Kg3cg2Z7EBMTz2HceHMIc8tAgrpXmNs2VFlDZgvbyUvA250mBW46uzxmCxf/9zRS5slZaFKMdQGGjRI9u/I35EluvGBvL3rVFONPowTWRasOpREYgC2fWh8sF2/FkoyQjKc8qdyhli0cSaNsVmBAO77sWceK6LJEN5G6V46pSuFymnlHPi2yVo5HZ3d8VzWhn/7RPeRxRl9PjSJEWj3MjevNc=
  template:
    metadata:
      name: ragflow-config
      namespace: ragflow
