---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: ai-tools
spec:
  encryptedData:
    secret-key: AgBKNdbUATEAYNlrvREX5wZwcWNJJRjUBD3Tr7LFi9/Rmm3LArazzzf0XC6hmL3Ii6t/uYHgHO0IygvoPie1G6Sw6aAAAs8rPYrbgU04BlqR+Vd2KJ8JAT8d4tuvTjdP9CPGHB11dMrTTlIx2iD85IFVFTHeT2GlMVh15eqbpqckA0iYT4zzhNWxd5vfDpKpijahMmwUDZ94SyqMJi6i4Bm+Sxo9WKiw/AIpN6Ap1qqQd++bs6zDli+cCmzyGusPCz2swePbx3DzAo9sjl5bo93ZXqlNMGtCvCDFyDYobHsc8AM7bCfht2t/6oMVhpcOQG/DhHsRxLML8kPlVxLQtMk5NZwhljp734Ury5/iiWQFX+R19kvJ9T20AEqC6P1Pt60byyQMZsVMHM18V4XbAda428Vlwov6c9PGbg1DtP4SQYT4Bnsras0Swj43C7VJMOTlfACHGx80buohceHA7KYwlWOjdN/H8QOL5rdgSbbCPxzTf2HBMSbEZjthoLAsZMtuFmyGzz1ISUBoowpMs2bIxYnvZvBn7W6WWDyFik4RX6A65Qteae0dPmvRBL2VWDvCl/Pj2Epb1GPh3o8nBzdQn7kVYeF2sdlnQALvL4HMRs3ULh2tDPt0xy1mxRYkZGSaKGEkJQDq7lqZUjZ+IS24fOLKrI6WtFmKjoA1YU0bgbMysTgFr30YVRWs7878KGXI7p2Vqk0M8W8QExRm/62YaoYjxP6ijG0CRk+Iy8rOZmH1fUtyzrjUsHkA9v7e2CoZTmwAocMg1Ioq5EYQSqmi
  template:
    metadata:
      name: open-webui-secret
      namespace: ai-tools
    type: Opaque
