---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: ai-tools
spec:
  encryptedData:
    secret-key: AgBWuwmyP6/04u90MIutvizgeneFbDzP1R70i7vCKVwCcxo3byYPXnpeC60oVBhiMzvKt5EGOEH5j7u27Lztneko7fhdohsiV7cqi9NsL9WIp0y4sAN5O//ZbzrUIPR3ooQFOdczS0GElHl7PnvygPaQqrH+FrKJhvX/QTAvmO3rlIA9+UfZAURqpkRKeMzLlo0C7vCDi2iawm/qZWD3/ptPXmiK7q4hOo613n2CzFbO9OIPduja55zu45OVIesRBWQ+WsXuLfzUED5p6Ak2ugluRLTwgbw3t/22PA75r84e1zeDYz8fyFQ9XHAC3sjdKY8TQ+sN4LQY0mqVcjefdTxcncjJOp0GSatjBPH0xy/7hOyE0B72jFc4pxJZQuF897BVY0rgO+XQPoMQU3H860QAjsfzujuWWvOOc4BWH32l94EemZFThLlhJUKBzk3bFWq30ZI1mViKoEgNoi3Geib9z86tSfba4hBp8JpNOnSa+wjSdLphSXLUpSJ9Xfm1IpFDKJcAjK4HyTJw6ozqQZVEKwv8A6Ac04tNXRE5Lp5F6tbAuGeJwixz/ZtLRRS0/9tuAFZhbHwXv7g1d1E9CY5mPjwK2Oi2kRFzglku4sowF/Pq4fvEQtWdKKmsE3uR0lX0/70HFHGbQv0bezkHcGryv8kPGYCAnC1L9JNB13WT6Un9Ezu+G0j7ypQIpVjdkEJyTDEUxLYAX67nkz+VG0jYmYl64aMxSlNEj1UNFO26+rYIRd3tTnS0LcFLcXt15/LtIi0JQOfIwbF6Ep19gJd2
  template:
    metadata:
      name: searxng-secret
      namespace: ai-tools
    type: Opaque
